name: Create PySide6 exe with Nuitka-Action

on:
  push:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest] # [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
          cache: 'pip'

      - name: Install system dependencies
        run: |
          # APT update
          sudo apt update

          # Install Pyside6 system dependencies
          sudo apt install -y \
            libfontconfig1-dev libfreetype6-dev \
            libx11-dev libx11-xcb-dev libxext-dev libxfixes-dev \
            libxi-dev libxrender-dev \
            libxkbcommon-dev libxkbcommon-x11-dev libatspi2.0-dev \
            libopengl0 '^libxcb.*-dev' \
            libgl1 libegl1 libdbus-glib-1-2

          # Install Nuitka dependencies
          sudo apt install -y \
            ccache \
            clang \
            patchelf
            
          # Build dependencies
          sudo apt install -y \
            python3-virtualenv

      - name: Install Dependencies / Build
        run: |
          # Create virtual environment
          virtualenv venv
          source venv/bin/activate

          # Install project requirements
          pip install -r requirements.txt

          # Create executables
          pyside6-deploy -c pysidedeploy.spec

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }} Build
          path: |
            main
            main.exe

